name: iOS starter workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build and Test default scheme using any available iPhone simulator
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set XCode version
        run: sudo xcode-select -s /Applications/Xcode_10.3.app/Contents/Developer
      - name: Resolve dependencies with Carthage
        run: carthage update 
      - name: Set Default Scheme
        run: |
          scheme_list=$(xcodebuild -list -json | tr -d "\n")
          default=$(echo $scheme_list | ruby -e "require 'json'; puts JSON.parse(STDIN.gets)['project']['targets'][0]")
          echo $default | cat >default
          echo Using default scheme: $default
          echo ${{ secrets.PROVISIONING_PROFILE }}
      - name: Build
        env:
          scheme: ${{ 'default' }}
          platform: ${{ 'iOS Simulator' }}
        run: |
          ls -l -R Carthage
          device=`instruments -s -devices | grep -oE 'iPhone.*?[^\(]+' | head -1 | awk '{$1=$1;print}'`
          if [ $scheme = default ]; then scheme=$(cat default); fi
          xcodebuild build -scheme "$scheme" -workspace "15 Universe Facts.xcodeproj/15-universe-facts.xcworkspace" -destination "platform=$platform,name=$device"
