name: iOS starter workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build and Test default scheme using any available iPhone simulator
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set XCode version
        run: sudo xcode-select -s /Applications/Xcode_10.3.app/Contents/Developer
      - name: Resolve dependencies with Carthage
        run: carthage update 
      - name: Setup provisioning profile and certificate
        run: |
          echo -n "${{ secrets.DISTRIBUTION_CERTIFICATE }}" | base64 --decode --output certificate.p12
          echo -n "${{ secrets.PROVISIONING_PROFILE }}" | base64 --decode --output ${{ secrets.PROVISION_FILE_NAME }}
          KEYCHAIN_PATH=$RUNNER_TEMP/15factskeychain
          security create-keychain -p ${{ secrets.KEYCHAIN_PASS }} $KEYCHAIN_PATH
          security set-keychain-settings -lut 21600 $KEYCHAIN_PATH
          security unlock-keychain -p ${{ secrets.KEYCHAIN_PASS }} $KEYCHAIN_PATH
          security import certificate.p12 -P ${{ secrets.CERTIFICATE_PASS }} -A -t cert -f pkcs12 -k $KEYCHAIN_PATH
          security list-keychain -d user -s $KEYCHAIN_PATH
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          cp ${{ secrets.PROVISION_FILE_NAME }} ~/Library/MobileDevice/Provisioning\ Profiles        
      - name: Build to Archive
        run: |
          mkdir output
          xcodebuild build -scheme "15 Universe Facts" -workspace "15 Universe Facts.xcodeproj/15-universe-facts.xcworkspace"  -allowProvisioningUpdates -archivePath output/15-universe-facts.xcarchive archive
      - name: Export IPA
        run: |
          mkdir output
          xcodebuild -exportArchive -archivePath output/15-universe-facts.xcarchive/ -exportPath ./output -exportOptionsPlist exportOptions.plist -allowProvisioningUpdates

